#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oteltakip
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="oteltakip")]
	public partial class oteltakipDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkullanicihesaplari(kullanicihesaplari instance);
    partial void Updatekullanicihesaplari(kullanicihesaplari instance);
    partial void Deletekullanicihesaplari(kullanicihesaplari instance);
    partial void Insertsorusor(sorusor instance);
    partial void Updatesorusor(sorusor instance);
    partial void Deletesorusor(sorusor instance);
    partial void Insertsiparistablosu(siparistablosu instance);
    partial void Updatesiparistablosu(siparistablosu instance);
    partial void Deletesiparistablosu(siparistablosu instance);
    partial void Insertgmusteriler(gmusteriler instance);
    partial void Updategmusteriler(gmusteriler instance);
    partial void Deletegmusteriler(gmusteriler instance);
    partial void Insertodadurumu(odadurumu instance);
    partial void Updateodadurumu(odadurumu instance);
    partial void Deleteodadurumu(odadurumu instance);
    partial void Insertrezervasyon1(rezervasyon1 instance);
    partial void Updaterezervasyon1(rezervasyon1 instance);
    partial void Deleterezervasyon1(rezervasyon1 instance);
    partial void Insertmisafir1(misafir1 instance);
    partial void Updatemisafir1(misafir1 instance);
    partial void Deletemisafir1(misafir1 instance);
    partial void Insertmusterihesaplari(musterihesaplari instance);
    partial void Updatemusterihesaplari(musterihesaplari instance);
    partial void Deletemusterihesaplari(musterihesaplari instance);
    partial void Inserttemizlik(temizlik instance);
    partial void Updatetemizlik(temizlik instance);
    partial void Deletetemizlik(temizlik instance);
    partial void Insertmusteriler(musteriler instance);
    partial void Updatemusteriler(musteriler instance);
    partial void Deletemusteriler(musteriler instance);
    #endregion
		
		public oteltakipDataContext() : 
				base(global::oteltakip.Properties.Settings.Default.oteltakipConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public oteltakipDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public oteltakipDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public oteltakipDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public oteltakipDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kullanicihesaplari> kullanicihesaplaris
		{
			get
			{
				return this.GetTable<kullanicihesaplari>();
			}
		}
		
		public System.Data.Linq.Table<sorusor> sorusors
		{
			get
			{
				return this.GetTable<sorusor>();
			}
		}
		
		public System.Data.Linq.Table<siparistablosu> siparistablosus
		{
			get
			{
				return this.GetTable<siparistablosu>();
			}
		}
		
		public System.Data.Linq.Table<gmusteriler> gmusterilers
		{
			get
			{
				return this.GetTable<gmusteriler>();
			}
		}
		
		public System.Data.Linq.Table<kisisayisi> kisisayisis
		{
			get
			{
				return this.GetTable<kisisayisi>();
			}
		}
		
		public System.Data.Linq.Table<odadurumu> odadurumus
		{
			get
			{
				return this.GetTable<odadurumu>();
			}
		}
		
		public System.Data.Linq.Table<rezervasyon1> rezervasyon1s
		{
			get
			{
				return this.GetTable<rezervasyon1>();
			}
		}
		
		public System.Data.Linq.Table<misafir1> misafir1s
		{
			get
			{
				return this.GetTable<misafir1>();
			}
		}
		
		public System.Data.Linq.Table<musterihesaplari> musterihesaplaris
		{
			get
			{
				return this.GetTable<musterihesaplari>();
			}
		}
		
		public System.Data.Linq.Table<temizlik> temizliks
		{
			get
			{
				return this.GetTable<temizlik>();
			}
		}
		
		public System.Data.Linq.Table<musteriler> musterilers
		{
			get
			{
				return this.GetTable<musteriler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kullanicihesaplari")]
	public partial class kullanicihesaplari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kullaniciadi;
		
		private string _sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkullaniciadiChanging(string value);
    partial void OnkullaniciadiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    #endregion
		
		public kullanicihesaplari()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciadi", DbType="VarChar(20)", IsPrimaryKey=true)]
		public string kullaniciadi
		{
			get
			{
				return this._kullaniciadi;
			}
			set
			{
				if ((this._kullaniciadi != value))
				{
					this.OnkullaniciadiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciadi = value;
					this.SendPropertyChanged("kullaniciadi");
					this.OnkullaniciadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="VarChar(20)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sorusor")]
	public partial class sorusor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _soru;
		
		private string _cevap;
		
		private string _sorankisitc;
		
		private string _cevaplayankisikadi;
		
		private string _soruno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsoruChanging(string value);
    partial void OnsoruChanged();
    partial void OncevapChanging(string value);
    partial void OncevapChanged();
    partial void OnsorankisitcChanging(string value);
    partial void OnsorankisitcChanged();
    partial void OncevaplayankisikadiChanging(string value);
    partial void OncevaplayankisikadiChanged();
    partial void OnsorunoChanging(string value);
    partial void OnsorunoChanged();
    #endregion
		
		public sorusor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soru", DbType="VarChar(200)")]
		public string soru
		{
			get
			{
				return this._soru;
			}
			set
			{
				if ((this._soru != value))
				{
					this.OnsoruChanging(value);
					this.SendPropertyChanging();
					this._soru = value;
					this.SendPropertyChanged("soru");
					this.OnsoruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cevap", DbType="VarChar(200)")]
		public string cevap
		{
			get
			{
				return this._cevap;
			}
			set
			{
				if ((this._cevap != value))
				{
					this.OncevapChanging(value);
					this.SendPropertyChanging();
					this._cevap = value;
					this.SendPropertyChanged("cevap");
					this.OncevapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sorankisitc", DbType="VarChar(11)")]
		public string sorankisitc
		{
			get
			{
				return this._sorankisitc;
			}
			set
			{
				if ((this._sorankisitc != value))
				{
					this.OnsorankisitcChanging(value);
					this.SendPropertyChanging();
					this._sorankisitc = value;
					this.SendPropertyChanged("sorankisitc");
					this.OnsorankisitcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cevaplayankisikadi", DbType="VarChar(30)")]
		public string cevaplayankisikadi
		{
			get
			{
				return this._cevaplayankisikadi;
			}
			set
			{
				if ((this._cevaplayankisikadi != value))
				{
					this.OncevaplayankisikadiChanging(value);
					this.SendPropertyChanging();
					this._cevaplayankisikadi = value;
					this.SendPropertyChanged("cevaplayankisikadi");
					this.OncevaplayankisikadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soruno", CanBeNull=false, IsPrimaryKey=true)]
		public string soruno
		{
			get
			{
				return this._soruno;
			}
			set
			{
				if ((this._soruno != value))
				{
					this.OnsorunoChanging(value);
					this.SendPropertyChanging();
					this._soruno = value;
					this.SendPropertyChanged("soruno");
					this.OnsorunoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.siparistablosu")]
	public partial class siparistablosu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sip_no;
		
		private string _mustc;
		
		private string _siparisliste;
		
		private System.Nullable<int> _siparis_tutar;
		
		private string _siparis_tarihi;
		
		private string _onaylayanpersonel;
		
		private string _teslim_tarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsip_noChanging(int value);
    partial void Onsip_noChanged();
    partial void OnmustcChanging(string value);
    partial void OnmustcChanged();
    partial void OnsiparislisteChanging(string value);
    partial void OnsiparislisteChanged();
    partial void Onsiparis_tutarChanging(System.Nullable<int> value);
    partial void Onsiparis_tutarChanged();
    partial void Onsiparis_tarihiChanging(string value);
    partial void Onsiparis_tarihiChanged();
    partial void OnonaylayanpersonelChanging(string value);
    partial void OnonaylayanpersonelChanged();
    partial void Onteslim_tarihiChanging(string value);
    partial void Onteslim_tarihiChanged();
    #endregion
		
		public siparistablosu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sip_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sip_no
		{
			get
			{
				return this._sip_no;
			}
			set
			{
				if ((this._sip_no != value))
				{
					this.Onsip_noChanging(value);
					this.SendPropertyChanging();
					this._sip_no = value;
					this.SendPropertyChanged("sip_no");
					this.Onsip_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mustc", DbType="VarChar(11)")]
		public string mustc
		{
			get
			{
				return this._mustc;
			}
			set
			{
				if ((this._mustc != value))
				{
					this.OnmustcChanging(value);
					this.SendPropertyChanging();
					this._mustc = value;
					this.SendPropertyChanged("mustc");
					this.OnmustcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisliste", DbType="VarChar(300)")]
		public string siparisliste
		{
			get
			{
				return this._siparisliste;
			}
			set
			{
				if ((this._siparisliste != value))
				{
					this.OnsiparislisteChanging(value);
					this.SendPropertyChanging();
					this._siparisliste = value;
					this.SendPropertyChanged("siparisliste");
					this.OnsiparislisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_tutar", DbType="Int")]
		public System.Nullable<int> siparis_tutar
		{
			get
			{
				return this._siparis_tutar;
			}
			set
			{
				if ((this._siparis_tutar != value))
				{
					this.Onsiparis_tutarChanging(value);
					this.SendPropertyChanging();
					this._siparis_tutar = value;
					this.SendPropertyChanged("siparis_tutar");
					this.Onsiparis_tutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_tarihi", DbType="VarChar(40)")]
		public string siparis_tarihi
		{
			get
			{
				return this._siparis_tarihi;
			}
			set
			{
				if ((this._siparis_tarihi != value))
				{
					this.Onsiparis_tarihiChanging(value);
					this.SendPropertyChanging();
					this._siparis_tarihi = value;
					this.SendPropertyChanged("siparis_tarihi");
					this.Onsiparis_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onaylayanpersonel", DbType="VarChar(30)")]
		public string onaylayanpersonel
		{
			get
			{
				return this._onaylayanpersonel;
			}
			set
			{
				if ((this._onaylayanpersonel != value))
				{
					this.OnonaylayanpersonelChanging(value);
					this.SendPropertyChanging();
					this._onaylayanpersonel = value;
					this.SendPropertyChanged("onaylayanpersonel");
					this.OnonaylayanpersonelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teslim_tarihi", DbType="VarChar(40)")]
		public string teslim_tarihi
		{
			get
			{
				return this._teslim_tarihi;
			}
			set
			{
				if ((this._teslim_tarihi != value))
				{
					this.Onteslim_tarihiChanging(value);
					this.SendPropertyChanging();
					this._teslim_tarihi = value;
					this.SendPropertyChanged("teslim_tarihi");
					this.Onteslim_tarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gmusteriler")]
	public partial class gmusteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tckimlikno;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _ceptelefonu;
		
		private string _cinsiyeti;
		
		private string _giristarihi;
		
		private string _cikistarihi;
		
		private string _odaturu;
		
		private string _kaldigioda;
		
		private string _odedigiucret;
		
		private string _resimi;
		
		private int _numara;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntckimliknoChanging(string value);
    partial void OntckimliknoChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnceptelefonuChanging(string value);
    partial void OnceptelefonuChanged();
    partial void OncinsiyetiChanging(string value);
    partial void OncinsiyetiChanged();
    partial void OngiristarihiChanging(string value);
    partial void OngiristarihiChanged();
    partial void OncikistarihiChanging(string value);
    partial void OncikistarihiChanged();
    partial void OnodaturuChanging(string value);
    partial void OnodaturuChanged();
    partial void OnkaldigiodaChanging(string value);
    partial void OnkaldigiodaChanged();
    partial void OnodedigiucretChanging(string value);
    partial void OnodedigiucretChanged();
    partial void OnresimiChanging(string value);
    partial void OnresimiChanged();
    partial void OnnumaraChanging(int value);
    partial void OnnumaraChanged();
    #endregion
		
		public gmusteriler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tckimlikno", DbType="VarChar(11)")]
		public string tckimlikno
		{
			get
			{
				return this._tckimlikno;
			}
			set
			{
				if ((this._tckimlikno != value))
				{
					this.OntckimliknoChanging(value);
					this.SendPropertyChanging();
					this._tckimlikno = value;
					this.SendPropertyChanged("tckimlikno");
					this.OntckimliknoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(30)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="VarChar(30)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ceptelefonu", DbType="VarChar(30)")]
		public string ceptelefonu
		{
			get
			{
				return this._ceptelefonu;
			}
			set
			{
				if ((this._ceptelefonu != value))
				{
					this.OnceptelefonuChanging(value);
					this.SendPropertyChanging();
					this._ceptelefonu = value;
					this.SendPropertyChanged("ceptelefonu");
					this.OnceptelefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyeti", DbType="VarChar(5)")]
		public string cinsiyeti
		{
			get
			{
				return this._cinsiyeti;
			}
			set
			{
				if ((this._cinsiyeti != value))
				{
					this.OncinsiyetiChanging(value);
					this.SendPropertyChanging();
					this._cinsiyeti = value;
					this.SendPropertyChanged("cinsiyeti");
					this.OncinsiyetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giristarihi", DbType="VarChar(100)")]
		public string giristarihi
		{
			get
			{
				return this._giristarihi;
			}
			set
			{
				if ((this._giristarihi != value))
				{
					this.OngiristarihiChanging(value);
					this.SendPropertyChanging();
					this._giristarihi = value;
					this.SendPropertyChanged("giristarihi");
					this.OngiristarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cikistarihi", DbType="VarChar(100)")]
		public string cikistarihi
		{
			get
			{
				return this._cikistarihi;
			}
			set
			{
				if ((this._cikistarihi != value))
				{
					this.OncikistarihiChanging(value);
					this.SendPropertyChanging();
					this._cikistarihi = value;
					this.SendPropertyChanged("cikistarihi");
					this.OncikistarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaturu", DbType="VarChar(30)")]
		public string odaturu
		{
			get
			{
				return this._odaturu;
			}
			set
			{
				if ((this._odaturu != value))
				{
					this.OnodaturuChanging(value);
					this.SendPropertyChanging();
					this._odaturu = value;
					this.SendPropertyChanged("odaturu");
					this.OnodaturuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaldigioda", DbType="VarChar(7)")]
		public string kaldigioda
		{
			get
			{
				return this._kaldigioda;
			}
			set
			{
				if ((this._kaldigioda != value))
				{
					this.OnkaldigiodaChanging(value);
					this.SendPropertyChanging();
					this._kaldigioda = value;
					this.SendPropertyChanged("kaldigioda");
					this.OnkaldigiodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odedigiucret", DbType="VarChar(10)")]
		public string odedigiucret
		{
			get
			{
				return this._odedigiucret;
			}
			set
			{
				if ((this._odedigiucret != value))
				{
					this.OnodedigiucretChanging(value);
					this.SendPropertyChanging();
					this._odedigiucret = value;
					this.SendPropertyChanged("odedigiucret");
					this.OnodedigiucretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resimi", DbType="VarChar(200)")]
		public string resimi
		{
			get
			{
				return this._resimi;
			}
			set
			{
				if ((this._resimi != value))
				{
					this.OnresimiChanging(value);
					this.SendPropertyChanging();
					this._resimi = value;
					this.SendPropertyChanged("resimi");
					this.OnresimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numara", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numara
		{
			get
			{
				return this._numara;
			}
			set
			{
				if ((this._numara != value))
				{
					this.OnnumaraChanging(value);
					this.SendPropertyChanging();
					this._numara = value;
					this.SendPropertyChanged("numara");
					this.OnnumaraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kisisayisi")]
	public partial class kisisayisi
	{
		
		private System.Nullable<int> _kisisayi;
		
		public kisisayisi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kisisayi", DbType="Int")]
		public System.Nullable<int> kisisayi
		{
			get
			{
				return this._kisisayi;
			}
			set
			{
				if ((this._kisisayi != value))
				{
					this._kisisayi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.odadurumu")]
	public partial class odadurumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _odano;
		
		private string _odadurumu1;
		
		private string _odanoo;
		
		private string _turu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnodanoChanging(int value);
    partial void OnodanoChanged();
    partial void Onodadurumu1Changing(string value);
    partial void Onodadurumu1Changed();
    partial void OnodanooChanging(string value);
    partial void OnodanooChanged();
    partial void OnturuChanging(string value);
    partial void OnturuChanged();
    #endregion
		
		public odadurumu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odano", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int odano
		{
			get
			{
				return this._odano;
			}
			set
			{
				if ((this._odano != value))
				{
					this.OnodanoChanging(value);
					this.SendPropertyChanging();
					this._odano = value;
					this.SendPropertyChanged("odano");
					this.OnodanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="odadurumu", Storage="_odadurumu1", DbType="VarChar(20)")]
		public string odadurumu1
		{
			get
			{
				return this._odadurumu1;
			}
			set
			{
				if ((this._odadurumu1 != value))
				{
					this.Onodadurumu1Changing(value);
					this.SendPropertyChanging();
					this._odadurumu1 = value;
					this.SendPropertyChanged("odadurumu1");
					this.Onodadurumu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odanoo", DbType="VarChar(2)")]
		public string odanoo
		{
			get
			{
				return this._odanoo;
			}
			set
			{
				if ((this._odanoo != value))
				{
					this.OnodanooChanging(value);
					this.SendPropertyChanging();
					this._odanoo = value;
					this.SendPropertyChanged("odanoo");
					this.OnodanooChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turu", DbType="VarChar(20)")]
		public string turu
		{
			get
			{
				return this._turu;
			}
			set
			{
				if ((this._turu != value))
				{
					this.OnturuChanging(value);
					this.SendPropertyChanging();
					this._turu = value;
					this.SendPropertyChanged("turu");
					this.OnturuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rezervasyon")]
	public partial class rezervasyon1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _r_no;
		
		private string _tckimlik;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _giristarihi;
		
		private string _cikistarihi;
		
		private string _ceptel;
		
		private string _oda__no;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onr_noChanging(int value);
    partial void Onr_noChanged();
    partial void OntckimlikChanging(string value);
    partial void OntckimlikChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OngiristarihiChanging(string value);
    partial void OngiristarihiChanged();
    partial void OncikistarihiChanging(string value);
    partial void OncikistarihiChanged();
    partial void OnceptelChanging(string value);
    partial void OnceptelChanged();
    partial void Onoda__noChanging(string value);
    partial void Onoda__noChanged();
    #endregion
		
		public rezervasyon1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int r_no
		{
			get
			{
				return this._r_no;
			}
			set
			{
				if ((this._r_no != value))
				{
					this.Onr_noChanging(value);
					this.SendPropertyChanging();
					this._r_no = value;
					this.SendPropertyChanged("r_no");
					this.Onr_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tckimlik", DbType="VarChar(11)")]
		public string tckimlik
		{
			get
			{
				return this._tckimlik;
			}
			set
			{
				if ((this._tckimlik != value))
				{
					this.OntckimlikChanging(value);
					this.SendPropertyChanging();
					this._tckimlik = value;
					this.SendPropertyChanged("tckimlik");
					this.OntckimlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(30)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="VarChar(30)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giristarihi", DbType="VarChar(100)")]
		public string giristarihi
		{
			get
			{
				return this._giristarihi;
			}
			set
			{
				if ((this._giristarihi != value))
				{
					this.OngiristarihiChanging(value);
					this.SendPropertyChanging();
					this._giristarihi = value;
					this.SendPropertyChanged("giristarihi");
					this.OngiristarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cikistarihi", DbType="VarChar(100)")]
		public string cikistarihi
		{
			get
			{
				return this._cikistarihi;
			}
			set
			{
				if ((this._cikistarihi != value))
				{
					this.OncikistarihiChanging(value);
					this.SendPropertyChanging();
					this._cikistarihi = value;
					this.SendPropertyChanged("cikistarihi");
					this.OncikistarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ceptel", DbType="VarChar(11)")]
		public string ceptel
		{
			get
			{
				return this._ceptel;
			}
			set
			{
				if ((this._ceptel != value))
				{
					this.OnceptelChanging(value);
					this.SendPropertyChanging();
					this._ceptel = value;
					this.SendPropertyChanged("ceptel");
					this.OnceptelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oda__no", DbType="VarChar(6)")]
		public string oda__no
		{
			get
			{
				return this._oda__no;
			}
			set
			{
				if ((this._oda__no != value))
				{
					this.Onoda__noChanging(value);
					this.SendPropertyChanging();
					this._oda__no = value;
					this.SendPropertyChanged("oda__no");
					this.Onoda__noChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.misafir")]
	public partial class misafir1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _m_no;
		
		private string _geldigioda;
		
		private string _isim;
		
		private string _soyisim;
		
		private string _ceptel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onm_noChanging(int value);
    partial void Onm_noChanged();
    partial void OngeldigiodaChanging(string value);
    partial void OngeldigiodaChanged();
    partial void OnisimChanging(string value);
    partial void OnisimChanged();
    partial void OnsoyisimChanging(string value);
    partial void OnsoyisimChanged();
    partial void OnceptelChanging(string value);
    partial void OnceptelChanged();
    #endregion
		
		public misafir1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int m_no
		{
			get
			{
				return this._m_no;
			}
			set
			{
				if ((this._m_no != value))
				{
					this.Onm_noChanging(value);
					this.SendPropertyChanging();
					this._m_no = value;
					this.SendPropertyChanged("m_no");
					this.Onm_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geldigioda", DbType="VarChar(6)")]
		public string geldigioda
		{
			get
			{
				return this._geldigioda;
			}
			set
			{
				if ((this._geldigioda != value))
				{
					this.OngeldigiodaChanging(value);
					this.SendPropertyChanging();
					this._geldigioda = value;
					this.SendPropertyChanged("geldigioda");
					this.OngeldigiodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isim", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string isim
		{
			get
			{
				return this._isim;
			}
			set
			{
				if ((this._isim != value))
				{
					this.OnisimChanging(value);
					this.SendPropertyChanging();
					this._isim = value;
					this.SendPropertyChanged("isim");
					this.OnisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyisim", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string soyisim
		{
			get
			{
				return this._soyisim;
			}
			set
			{
				if ((this._soyisim != value))
				{
					this.OnsoyisimChanging(value);
					this.SendPropertyChanging();
					this._soyisim = value;
					this.SendPropertyChanged("soyisim");
					this.OnsoyisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ceptel", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string ceptel
		{
			get
			{
				return this._ceptel;
			}
			set
			{
				if ((this._ceptel != value))
				{
					this.OnceptelChanging(value);
					this.SendPropertyChanging();
					this._ceptel = value;
					this.SendPropertyChanged("ceptel");
					this.OnceptelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.musterihesaplari")]
	public partial class musterihesaplari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kullaniciadi;
		
		private string _sifre;
		
		private int _numarasi;
		
		private string _oda_numarasi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkullaniciadiChanging(string value);
    partial void OnkullaniciadiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnnumarasiChanging(int value);
    partial void OnnumarasiChanged();
    partial void Onoda_numarasiChanging(string value);
    partial void Onoda_numarasiChanged();
    #endregion
		
		public musterihesaplari()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciadi", DbType="VarChar(11)")]
		public string kullaniciadi
		{
			get
			{
				return this._kullaniciadi;
			}
			set
			{
				if ((this._kullaniciadi != value))
				{
					this.OnkullaniciadiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciadi = value;
					this.SendPropertyChanged("kullaniciadi");
					this.OnkullaniciadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="VarChar(11)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numarasi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numarasi
		{
			get
			{
				return this._numarasi;
			}
			set
			{
				if ((this._numarasi != value))
				{
					this.OnnumarasiChanging(value);
					this.SendPropertyChanging();
					this._numarasi = value;
					this.SendPropertyChanged("numarasi");
					this.OnnumarasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oda_numarasi", DbType="VarChar(6)")]
		public string oda_numarasi
		{
			get
			{
				return this._oda_numarasi;
			}
			set
			{
				if ((this._oda_numarasi != value))
				{
					this.Onoda_numarasiChanging(value);
					this.SendPropertyChanging();
					this._oda_numarasi = value;
					this.SendPropertyChanged("oda_numarasi");
					this.Onoda_numarasiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.temizlik")]
	public partial class temizlik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tno;
		
		private string _odano;
		
		private string _t_tarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntnoChanging(int value);
    partial void OntnoChanged();
    partial void OnodanoChanging(string value);
    partial void OnodanoChanged();
    partial void Ont_tarihiChanging(string value);
    partial void Ont_tarihiChanged();
    #endregion
		
		public temizlik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tno
		{
			get
			{
				return this._tno;
			}
			set
			{
				if ((this._tno != value))
				{
					this.OntnoChanging(value);
					this.SendPropertyChanging();
					this._tno = value;
					this.SendPropertyChanged("tno");
					this.OntnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odano", DbType="VarChar(6)")]
		public string odano
		{
			get
			{
				return this._odano;
			}
			set
			{
				if ((this._odano != value))
				{
					this.OnodanoChanging(value);
					this.SendPropertyChanging();
					this._odano = value;
					this.SendPropertyChanged("odano");
					this.OnodanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_tarihi", DbType="VarChar(50)")]
		public string t_tarihi
		{
			get
			{
				return this._t_tarihi;
			}
			set
			{
				if ((this._t_tarihi != value))
				{
					this.Ont_tarihiChanging(value);
					this.SendPropertyChanging();
					this._t_tarihi = value;
					this.SendPropertyChanged("t_tarihi");
					this.Ont_tarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.musteriler")]
	public partial class musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _musterino;
		
		private string _tckimlikno;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _ceptel;
		
		private string _giristarihi;
		
		private string _cikistarihi;
		
		private string _odaturu;
		
		private string _tutar;
		
		private string _odano;
		
		private string _bosmu;
		
		private string _cinsiyet;
		
		private string _resim;
		
		private string _anahtar;
		
		private System.Nullable<int> _kisisayisi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmusterinoChanging(int value);
    partial void OnmusterinoChanged();
    partial void OntckimliknoChanging(string value);
    partial void OntckimliknoChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnceptelChanging(string value);
    partial void OnceptelChanged();
    partial void OngiristarihiChanging(string value);
    partial void OngiristarihiChanged();
    partial void OncikistarihiChanging(string value);
    partial void OncikistarihiChanged();
    partial void OnodaturuChanging(string value);
    partial void OnodaturuChanged();
    partial void OntutarChanging(string value);
    partial void OntutarChanged();
    partial void OnodanoChanging(string value);
    partial void OnodanoChanged();
    partial void OnbosmuChanging(string value);
    partial void OnbosmuChanged();
    partial void OncinsiyetChanging(string value);
    partial void OncinsiyetChanged();
    partial void OnresimChanging(string value);
    partial void OnresimChanged();
    partial void OnanahtarChanging(string value);
    partial void OnanahtarChanged();
    partial void OnkisisayisiChanging(System.Nullable<int> value);
    partial void OnkisisayisiChanged();
    #endregion
		
		public musteriler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musterino", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int musterino
		{
			get
			{
				return this._musterino;
			}
			set
			{
				if ((this._musterino != value))
				{
					this.OnmusterinoChanging(value);
					this.SendPropertyChanging();
					this._musterino = value;
					this.SendPropertyChanged("musterino");
					this.OnmusterinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tckimlikno", DbType="VarChar(11)")]
		public string tckimlikno
		{
			get
			{
				return this._tckimlikno;
			}
			set
			{
				if ((this._tckimlikno != value))
				{
					this.OntckimliknoChanging(value);
					this.SendPropertyChanging();
					this._tckimlikno = value;
					this.SendPropertyChanged("tckimlikno");
					this.OntckimliknoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="VarChar(30)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="VarChar(30)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ceptel", DbType="VarChar(11)")]
		public string ceptel
		{
			get
			{
				return this._ceptel;
			}
			set
			{
				if ((this._ceptel != value))
				{
					this.OnceptelChanging(value);
					this.SendPropertyChanging();
					this._ceptel = value;
					this.SendPropertyChanged("ceptel");
					this.OnceptelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giristarihi", DbType="VarChar(100)")]
		public string giristarihi
		{
			get
			{
				return this._giristarihi;
			}
			set
			{
				if ((this._giristarihi != value))
				{
					this.OngiristarihiChanging(value);
					this.SendPropertyChanging();
					this._giristarihi = value;
					this.SendPropertyChanged("giristarihi");
					this.OngiristarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cikistarihi", DbType="VarChar(100)")]
		public string cikistarihi
		{
			get
			{
				return this._cikistarihi;
			}
			set
			{
				if ((this._cikistarihi != value))
				{
					this.OncikistarihiChanging(value);
					this.SendPropertyChanging();
					this._cikistarihi = value;
					this.SendPropertyChanged("cikistarihi");
					this.OncikistarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaturu", DbType="VarChar(20)")]
		public string odaturu
		{
			get
			{
				return this._odaturu;
			}
			set
			{
				if ((this._odaturu != value))
				{
					this.OnodaturuChanging(value);
					this.SendPropertyChanging();
					this._odaturu = value;
					this.SendPropertyChanged("odaturu");
					this.OnodaturuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tutar", DbType="VarChar(10)")]
		public string tutar
		{
			get
			{
				return this._tutar;
			}
			set
			{
				if ((this._tutar != value))
				{
					this.OntutarChanging(value);
					this.SendPropertyChanging();
					this._tutar = value;
					this.SendPropertyChanged("tutar");
					this.OntutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odano", DbType="VarChar(7)")]
		public string odano
		{
			get
			{
				return this._odano;
			}
			set
			{
				if ((this._odano != value))
				{
					this.OnodanoChanging(value);
					this.SendPropertyChanging();
					this._odano = value;
					this.SendPropertyChanged("odano");
					this.OnodanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bosmu", DbType="VarChar(5)")]
		public string bosmu
		{
			get
			{
				return this._bosmu;
			}
			set
			{
				if ((this._bosmu != value))
				{
					this.OnbosmuChanging(value);
					this.SendPropertyChanging();
					this._bosmu = value;
					this.SendPropertyChanged("bosmu");
					this.OnbosmuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="VarChar(5)")]
		public string cinsiyet
		{
			get
			{
				return this._cinsiyet;
			}
			set
			{
				if ((this._cinsiyet != value))
				{
					this.OncinsiyetChanging(value);
					this.SendPropertyChanging();
					this._cinsiyet = value;
					this.SendPropertyChanged("cinsiyet");
					this.OncinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resim", DbType="VarChar(200)")]
		public string resim
		{
			get
			{
				return this._resim;
			}
			set
			{
				if ((this._resim != value))
				{
					this.OnresimChanging(value);
					this.SendPropertyChanging();
					this._resim = value;
					this.SendPropertyChanged("resim");
					this.OnresimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anahtar", DbType="VarChar(100)")]
		public string anahtar
		{
			get
			{
				return this._anahtar;
			}
			set
			{
				if ((this._anahtar != value))
				{
					this.OnanahtarChanging(value);
					this.SendPropertyChanging();
					this._anahtar = value;
					this.SendPropertyChanged("anahtar");
					this.OnanahtarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kisisayisi", DbType="Int")]
		public System.Nullable<int> kisisayisi
		{
			get
			{
				return this._kisisayisi;
			}
			set
			{
				if ((this._kisisayisi != value))
				{
					this.OnkisisayisiChanging(value);
					this.SendPropertyChanging();
					this._kisisayisi = value;
					this.SendPropertyChanged("kisisayisi");
					this.OnkisisayisiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
